# This workflow determine which processor have changed,
# builds and pushes a Singularity container for each of those processor plugins

name: buildplugins

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps in the workflow
    
    steps:
      - name: Set up Python 3.6  # use this action since hpccm install fails with python installed by apt
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config \
            python3-dev \
            python3-pip \

      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 3.5.2
        run: |
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p /tmp/src/github.com/sylabs && \
          cd /tmp/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install && \
          mkdir ~/.singularity

      - name: Install hpccm
        run: |
          python3 -m pip install hpccm
    
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Track Changes
        id: track-changes
        uses: geoedf/track-changes-docker-action@v8
      - name: Output Folders
        run: echo "Connector plugins changed ${{ steps.track-changes.outputs.folders }}"
      - name: Loop and Build
        env:
          HPCCM_RECIPE: recipe.hpccm
          SINGULARITY_RECIPE: Singularity
          OUTPUT_CONTAINER: container.sif
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo $TOKEN | singularity remote add geoedf https://www.registry.geoedf.org
          singularity remote use geoedf
          singularity remote list
          dir=$(pwd)
          for folder in ${{ steps.track-changes.outputs.folders }}; do
              echo "Building processor plugin $folder"
              cd $dir/$folder
              if [ -f "${HPCCM_RECIPE}" ]; then
                hpccm --recipe ${HPCCM_RECIPE} --format singularity --singularity-version=3.2 > ${SINGULARITY_RECIPE}
              else
                echo "Container recipe ${HPCCM_RECIPE} not found."
              fi
              if [ -f "${SINGULARITY_RECIPE}" ]; then
                sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}

                if [ -f "${OUTPUT_CONTAINER}" ]; then
                  echo "library://geoedfproject/processors/$folder:latest"
                  singularity push -U ${OUTPUT_CONTAINER} library://geoedfproject/processors/$folder:latest
                else
                  echo "Container build failed."
                fi
              else
                echo "Singularity recipe ${SINGULARITY_RECIPE} was not created."
              fi
          done
